source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FloatingTextMenu', :exclusive => true do
  pod 'VKFloatingActionText', :git => 'https://github.com/vaghul/VKFoatingActionText.git'

  
end
